ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.colegio.HttpKt.configureHttp
      - com.colegio.SerializationKt.configureSerialization
      - com.colegio.RoutingKt.configureRouting
