ktor:
  deployment:
    port: 8080
    autoreload: false
  application:
    modules:
      - com.colegio.HttpKt.configureHttp
      - com.colegio.SerializationKt.configureSerialization
      - com.colegio.RoutingKt.configureRouting
      - com.colegio.WebSocketRoutingKt.configureSockets
